import { Roboto } from 'next/font/google';
import './globals.css';
import { StateProvider } from '@/context/page';


const roboto = Roboto({ 
  subsets: ['latin'], 
  weight: ['400','500','700',], 
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateProvider>
        <body className={roboto.className}>{children}</body>
      </StateProvider>
    </html>
  );
}
